import type { Framework } from '../types';

export const copywritingFrameworks: Framework[] = [
  {
    id: 'pas',
    name: 'PAS (Problem-Agitate-Solution)',
    category: 'copywriting',
    structure: ['Problem — name the core gap', 'Agitate — make the cost real and personal', 'Solution — introduce the relief'],
    whenToUse: 'Cold outreach where the prospect has a clear, nameable pain. Best when they may not realise how much the gap is costing them.',
    template: 'Open with a specific problem they have. Twist the knife gently — what is quietly happening because of that gap? Then position your service as the relief that removes it.',
    example: 'Salon has 89 reviews but no website. Problem: invisible online. Agitate: competitors with sites are capturing those searchers. Solution: a digital front door that works 24/7.',
    bestChannels: ['whatsapp', 'email'],
    bestTemperature: ['cold', 'warm'],
  },
  {
    id: 'aida',
    name: 'AIDA (Attention-Interest-Desire-Action)',
    category: 'copywriting',
    structure: ['Attention — stop them scrolling', 'Interest — build context and relevance', 'Desire — make them want the outcome', 'Action — one soft CTA'],
    whenToUse: 'Email and cold outreach where you have space to build a narrative arc.',
    template: 'Open with one sharp, specific observation. Build interest with a 2026-relevant insight (AI search, SEO). Make them desire the outcome (bookings while sleeping). Close with a soft CTA.',
    bestChannels: ['email'],
    bestTemperature: ['cold'],
  },
  {
    id: 'aidca',
    name: 'AIDCA (Attention-Interest-Desire-Conviction-Action)',
    category: 'copywriting',
    structure: ['Attention', 'Interest', 'Desire', 'Conviction — proof or specificity that removes doubt', 'Action'],
    whenToUse: 'Email cold outreach where the prospect needs a credibility signal before acting.',
    template: 'Same arc as AIDA but add one concrete proof element before the CTA: a real result, a specific feature, a named competitor who has the thing they lack.',
    bestChannels: ['email'],
    bestTemperature: ['cold', 'warm'],
  },
  {
    id: 'bab',
    name: 'BAB (Before-After-Bridge)',
    category: 'copywriting',
    structure: ['Before — their current reality', 'After — the desired future state', 'Bridge — your service is the path between'],
    whenToUse: 'Warm prospects or anyone who has shown awareness of the gap. The contrast makes the transformation feel achievable.',
    template: 'Paint their now: invisible online, losing customers they don\'t know they\'re losing. Paint the after: showing up when AI recommends local businesses. The bridge: your website service.',
    bestChannels: ['whatsapp', 'email'],
    bestTemperature: ['warm'],
  },
  {
    id: 'fab',
    name: 'FAB (Feature-Advantage-Benefit)',
    category: 'copywriting',
    structure: ['Feature — one specific aspect of what you build', 'Advantage — why it\'s better than what they have', 'Benefit — the personal outcome for them'],
    whenToUse: 'Follow-up or reply messages where the prospect already knows they need something but wants specifics.',
    template: 'Name one concrete feature (e.g. WhatsApp booking integration). Show why it beats their current setup (Instagram DMs aren\'t indexed). Land on their outcome (bookings while serving clients).',
    bestChannels: ['email', 'whatsapp'],
    bestTemperature: ['warm', 'hot'],
  },
  {
    id: 'four_ps',
    name: '4Ps (Promise-Picture-Proof-Push)',
    category: 'copywriting',
    structure: ['Promise — clear, specific, concrete', 'Picture — vivid outcome', 'Proof — result, fact, or competitor comparison', 'Push — one decisive low-risk CTA'],
    whenToUse: 'Bold, conviction-building messages. Works well when you have a concrete result or comparison to use.',
    template: 'Open with a specific promise. Paint the vivid outcome. Back it with one proof point. Close with a decisive but low-risk push.',
    bestChannels: ['email'],
    bestTemperature: ['warm', 'hot'],
  },
  {
    id: 'pastor',
    name: 'PASTOR',
    category: 'copywriting',
    structure: ['Problem', 'Amplify', 'Story/Solution', 'Transformation', 'Offer', 'Response'],
    whenToUse: 'Longer email sequences or proposal cover emails where you have space for a full narrative.',
    template: 'Name the problem. Amplify the stakes. Tell a short story of a similar business that made the change. Show the transformation. Present the offer. Ask for a response.',
    bestChannels: ['email'],
    bestTemperature: ['warm', 'hot'],
  },
  {
    id: 'hso',
    name: 'HSO (Hook-Story-Offer)',
    category: 'copywriting',
    structure: ['Hook — one unexpected specific line', 'Story — brief relatable narrative (3 sentences max)', 'Offer — simple, low-friction, feels like a gift'],
    whenToUse: 'WhatsApp cold outreach where you need to feel like a real person, not a marketer.',
    template: 'Open with a specific line that shows you looked at their business. Tell a 3-sentence story about a similar business that made a change. Make a simple offer — free mockup, 5-minute idea.',
    bestChannels: ['whatsapp'],
    bestTemperature: ['cold'],
  },
  {
    id: 'sss',
    name: 'SSS (Star-Story-Solution)',
    category: 'copywriting',
    structure: ['Star — introduce the hero (similar business or the prospect themselves)', 'Story — their journey and the challenge they faced', 'Solution — how the problem was solved'],
    whenToUse: 'Second follow-up messages where social proof from a peer carries weight.',
    template: 'The prospect is the star. Tell their story back to them with empathy. Reveal the solution that changes the trajectory.',
    bestChannels: ['whatsapp', 'email'],
    bestTemperature: ['warm'],
  },
  {
    id: 'quest',
    name: 'QUEST',
    category: 'copywriting',
    structure: ['Qualify — confirm they are the right fit', 'Understand — show you understand their world', 'Educate — share one insight', 'Stimulate — spark desire', 'Transition — move to the next step'],
    whenToUse: 'Consultative cold outreach, especially for higher-ticket services.',
    template: 'Open by qualifying (you\'re talking to the right person). Show you understand their niche. Drop one useful insight. Make them want more. Transition to a next step.',
    bestChannels: ['email'],
    bestTemperature: ['cold', 'warm'],
  },
  {
    id: 'acca',
    name: 'ACCA (Awareness-Comprehension-Conviction-Action)',
    category: 'copywriting',
    structure: ['Awareness — surface the problem', 'Comprehension — help them understand why it matters', 'Conviction — build belief in the solution', 'Action — clear next step'],
    whenToUse: 'Prospects who are unaware of the gap. Educates without overwhelming.',
    template: 'Name the problem. Explain clearly why it costs them. Build conviction with specifics. Give one clear next step.',
    bestChannels: ['email'],
    bestTemperature: ['cold'],
  },
];
