import type { Framework } from '../types';

export const pitchFrameworks: Framework[] = [
  {
    id: 'storybrand',
    name: 'StoryBrand',
    category: 'pitch',
    structure: [
      'Character — the prospect is the hero with a goal',
      'Problem — external, internal, and philosophical layers',
      'Guide — you are the guide with a plan',
      'Plan — clear, simple steps',
      'Call to action — direct or transitional',
      'Success — the life they want',
      'Failure — what happens if they don\'t act',
    ],
    whenToUse: 'Proposals and longer emails. The business owner is always the hero — you are the guide, never the star.',
    template: 'Position the business owner as the hero with a goal (more customers, sustainable growth). You are the experienced guide. Present a clear 3-step plan. Show the success state and the cost of inaction.',
    bestChannels: ['email'],
    bestTemperature: ['warm', 'hot'],
  },
  {
    id: 'monroe',
    name: 'Monroe\'s Motivated Sequence',
    category: 'pitch',
    structure: [
      'Attention — hook',
      'Need — establish the problem',
      'Satisfaction — present the solution',
      'Visualisation — paint the outcome',
      'Action — CTA',
    ],
    whenToUse: 'Proposal emails and pitch decks. Classic persuasion sequence that moves from problem to vivid outcome.',
    template: 'Hook with a specific observation. Establish need clearly. Present the solution. Paint the vivid outcome they want. Close with action.',
    bestChannels: ['email'],
    bestTemperature: ['warm', 'hot'],
  },
  {
    id: 'pixar',
    name: 'Pixar Pitch',
    category: 'pitch',
    structure: [
      'Once upon a time... (situation)',
      'Every day... (routine)',
      'Until one day... (inciting incident / problem)',
      'Because of that... (consequence)',
      'Until finally... (resolution)',
      'And ever since then... (new normal)',
    ],
    whenToUse: 'Storytelling-heavy emails or follow-ups where emotional resonance matters more than logic.',
    template: 'Tell the story of a similar business. Once upon a time they had great reviews but no website. Every day they served clients. Until one day they realised competitors were capturing their searchers. Until finally they got a digital front door. And ever since, they\'ve had enquiries they never would have seen.',
    bestChannels: ['email'],
    bestTemperature: ['warm'],
  },
  {
    id: 'minto',
    name: 'Minto Pyramid (SCQA)',
    category: 'pitch',
    structure: [
      'Situation — shared context',
      'Complication — what changed or is wrong',
      'Question — the question that arises',
      'Answer — your solution',
    ],
    whenToUse: 'Consultative emails for analytical prospects who respect logical structure.',
    template: 'Establish shared context (they have X reviews, established business). Name the complication (2026 search is changing — AI recommends from websites). Surface the question it raises. Answer it clearly.',
    bestChannels: ['email'],
    bestTemperature: ['warm', 'hot'],
  },
  {
    id: 'proposal_spine',
    name: 'Proposal Spine',
    category: 'pitch',
    structure: [
      'Context — their situation as you understand it',
      'Objective — the outcome they want',
      'Approach — how you will achieve it',
      'Deliverables — what they get',
      'Investment — the cost',
      'Next steps — what happens after they say yes',
    ],
    whenToUse: 'Full project proposals. Provides the skeleton for any proposal document or email.',
    template: 'Open with their context (prove you understand their business). State the objective. Outline the approach. List deliverables concretely. State the investment clearly. Describe next steps.',
    bestChannels: ['email'],
    bestTemperature: ['hot'],
  },
  {
    id: 'what_so_what',
    name: 'What-So What-Now What',
    category: 'pitch',
    structure: [
      'What — state the fact or finding',
      'So What — explain why it matters to them specifically',
      'Now What — clear next step',
    ],
    whenToUse: 'Audit and weakness report emails. Communicates findings clearly without overwhelming.',
    template: 'State the finding. Explain the implication for this specific business. Give one actionable next step.',
    bestChannels: ['email', 'whatsapp'],
    bestTemperature: ['warm'],
  },
];
