import type { Framework } from '../types';

export const qualificationFrameworks: Framework[] = [
  {
    id: 'spin',
    name: 'SPIN (Situation-Problem-Implication-Need-Payoff)',
    category: 'qualification',
    structure: [
      'Situation — acknowledge their current setup',
      'Problem — surface the specific gap',
      'Implication — make the consequence real',
      'Need-Payoff — lead them to see the value themselves',
    ],
    whenToUse: 'Reply to interested prospects or second-touch follow-ups. Feels like a discovery conversation, not a pitch.',
    template: 'Acknowledge something real about their current situation. Surface one specific problem. Show what that problem is quietly costing them. Ask a payoff question: "What would it mean for your business if X?"',
    bestChannels: ['whatsapp', 'email'],
    bestTemperature: ['warm', 'hot'],
  },
  {
    id: 'bant',
    name: 'BANT (Budget-Authority-Need-Timeline)',
    category: 'qualification',
    structure: [
      'Budget — gauge willingness to invest',
      'Authority — confirm you are talking to the decision-maker',
      'Need — confirm the need is real',
      'Timeline — surface urgency',
    ],
    whenToUse: 'Discovery calls or email sequences for warmer prospects. Not for cold WhatsApp — too direct.',
    template: 'Use conversational questions to surface BANT signals without it feeling like an interrogation. Embed in a helpful framing.',
    bestChannels: ['email'],
    bestTemperature: ['warm', 'hot'],
  },
  {
    id: 'champ',
    name: 'CHAMP (Challenges-Authority-Money-Prioritisation)',
    category: 'qualification',
    structure: [
      'Challenges — lead with their challenges, not your product',
      'Authority — identify the decision-maker',
      'Money — budget conversation',
      'Prioritisation — how important is solving this now',
    ],
    whenToUse: 'Consultative email follow-up after initial interest. Leads with empathy, not budget.',
    template: 'Start with their challenges. Establish you are talking to the right person. Broach investment naturally. Ask how urgent the problem feels.',
    bestChannels: ['email'],
    bestTemperature: ['warm'],
  },
  {
    id: 'meddic',
    name: 'MEDDIC',
    category: 'qualification',
    structure: [
      'Metrics — quantify the impact',
      'Economic buyer — identify who controls the budget',
      'Decision criteria — understand how they decide',
      'Decision process — map the steps to a yes',
      'Identify pain — find the compelling pain',
      'Champion — find the internal advocate',
    ],
    whenToUse: 'Higher-value proposals where multiple decision-makers are involved. Overkill for SMB WhatsApp.',
    template: 'Use for proposal qualification. Map each element before writing the proposal.',
    bestChannels: ['email'],
    bestTemperature: ['hot'],
  },
  {
    id: 'gap',
    name: 'GAP (Goals-Actions-Problems)',
    category: 'qualification',
    structure: [
      'Goals — what does the prospect want to achieve',
      'Actions — what are they currently doing to achieve it',
      'Problems — where is the gap between actions and goals',
    ],
    whenToUse: 'Consultative discovery messages. Maps naturally onto the digital presence gap.',
    template: 'Ask about their goal (more customers, more bookings). Ask what they are currently doing (Instagram, referrals). Name the gap (those channels don\'t capture searchers).',
    bestChannels: ['email', 'whatsapp'],
    bestTemperature: ['warm'],
  },
  {
    id: 'neat',
    name: 'NEAT (Need-Economic Impact-Access-Timeline)',
    category: 'qualification',
    structure: [
      'Need — core need, not surface symptom',
      'Economic impact — quantify what solving it is worth',
      'Access — access to the right decision-maker',
      'Timeline — natural urgency',
    ],
    whenToUse: 'Focused qualification for mid-funnel email sequences.',
    template: 'Surface the real need. Put a number on it. Confirm access. Surface natural urgency.',
    bestChannels: ['email'],
    bestTemperature: ['warm', 'hot'],
  },
];
