import type { Metadata } from 'next';
import { SITE_URL, SITE_NAME } from '@/lib/seo';

export const metadata: Metadata = {
  title: 'Runvax vs Fiverr — Find Web Design Clients Without the Competition',
  description:
    'Tired of competing with hundreds of sellers on Fiverr? Runvax lets you find local businesses that need a website and pitch them directly — no bidding, no commission, no race to the bottom.',
  alternates: { canonical: `${SITE_URL}/vs-fiverr` },
  openGraph: {
    title: `Runvax vs Fiverr — Stop Waiting, Start Closing`,
    description:
      'Find unlimited web design leads without Fiverr commissions or competition. Search any city, contact businesses directly with AI cold outreach.',
    url: `${SITE_URL}/vs-fiverr`,
  },
};

const comparisons = [
  {
    feature: 'Finding clients',
    fiverr: 'Wait for buyers to find you among thousands of sellers',
    runvax: 'You actively find businesses that need a website right now',
  },
  {
    feature: 'Competition',
    fiverr: 'Compete with 50,000+ sellers on price, reviews, and gig ranking',
    runvax: 'You contact each prospect directly — no competing sellers',
  },
  {
    feature: 'Commission',
    fiverr: '20% commission taken on every sale',
    runvax: 'Zero commission — you keep 100% of every deal',
  },
  {
    feature: 'Client relationship',
    fiverr: 'Anonymous platform transactions, Fiverr owns the relationship',
    runvax: 'You own the client relationship from day one',
  },
  {
    feature: 'Pricing',
    fiverr: 'Race to the bottom — clients expect $5–$50 websites',
    runvax: 'You pitch directly at real market rates (₦50k–₦500k+)',
  },
  {
    feature: 'Outreach',
    fiverr: 'None — passive waiting for orders',
    runvax: 'AI-generated cold emails, WhatsApp messages, and proposals in one click',
  },
  {
    feature: 'Lead volume',
    fiverr: 'Depends on Fiverr algorithm ranking you high enough',
    runvax: 'Unlimited — search any city, any industry, anytime',
  },
  {
    feature: 'Cost',
    fiverr: '20% on every project (on a ₦50k job = ₦10k gone)',
    runvax: '₦9,999/month flat — keeps 100% of all revenue',
  },
];

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebPage',
  name: 'Runvax vs Fiverr',
  description:
    'Comparison of Runvax and Fiverr for web designers looking to find clients in Nigeria and Africa.',
  url: `${SITE_URL}/vs-fiverr`,
  mainEntity: {
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'Is Runvax better than Fiverr for finding web design clients?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'For web designers who want to find clients proactively — especially in Nigeria, Ghana, Kenya, and Africa — Runvax is far more effective than Fiverr. You search for businesses with no website, contact them directly with AI-generated outreach, and keep 100% of your revenue. Fiverr takes 20% commission and forces you to compete with thousands of sellers.',
        },
      },
      {
        '@type': 'Question',
        name: 'How do I find web design clients without Fiverr?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Use Runvax to search any city for businesses that have no website. Filter by industry (restaurants, salons, law firms, clinics, etc.), get their contact details, and send a personalized cold email or WhatsApp message generated by AI. You reach clients directly without any platform middleman or commission.',
        },
      },
    ],
  },
};

export default function VsFiverrPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <main className="min-h-screen bg-gray-950 text-white">
        <div className="max-w-4xl mx-auto px-4 py-16">
          {/* Hero */}
          <div className="text-center mb-16">
            <span className="inline-block text-xs font-semibold tracking-widest uppercase text-indigo-400 mb-3">
              Runvax vs Fiverr
            </span>
            <h1 className="text-4xl md:text-5xl font-bold mb-6 leading-tight">
              Stop Waiting for Fiverr Orders.<br />
              <span className="text-indigo-400">Go Find Your Clients.</span>
            </h1>
            <p className="text-gray-400 text-lg max-w-2xl mx-auto mb-8">
              Fiverr makes you compete with 50,000 sellers and takes 20% of every sale. Runvax
              lets you find businesses that need a website right now and pitch them directly — no
              competition, no commission.
            </p>
            <a
              href="/"
              className="inline-flex items-center gap-2 bg-indigo-600 hover:bg-indigo-500 transition-colors text-white font-semibold px-8 py-4 rounded-xl text-lg"
            >
              Find clients now — it&apos;s free →
            </a>
          </div>

          {/* Pain points */}
          <div className="mb-16 bg-red-950/30 border border-red-900/40 rounded-2xl p-8">
            <h2 className="text-2xl font-bold mb-6 text-red-400">The Fiverr Problem</h2>
            <ul className="space-y-4 text-gray-300">
              {[
                'You wait weeks for buyers to find your gig — meanwhile your rent is due.',
                'Your best gig gets buried by Fiverr\'s algorithm the moment a new competitor appears.',
                'Buyers expect ₦5,000 websites because Fiverr trained them to expect cheap.',
                'You lose ₦10,000 on every ₦50,000 project to commission — forever.',
                'You never own the client relationship — if Fiverr bans you, you lose everything.',
              ].map((point, i) => (
                <li key={i} className="flex items-start gap-3">
                  <span className="text-red-500 mt-0.5 shrink-0">✕</span>
                  <span>{point}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Comparison table */}
          <div className="mb-16">
            <h2 className="text-2xl font-bold mb-8 text-center">Side-by-Side Comparison</h2>
            <div className="overflow-x-auto rounded-2xl border border-gray-800">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-gray-900 border-b border-gray-800">
                    <th className="text-left px-6 py-4 text-gray-400 font-semibold w-1/4">Feature</th>
                    <th className="text-left px-6 py-4 text-red-400 font-semibold w-3/8">
                      🔴 Fiverr
                    </th>
                    <th className="text-left px-6 py-4 text-indigo-400 font-semibold w-3/8">
                      🟢 Runvax
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {comparisons.map((row, i) => (
                    <tr
                      key={i}
                      className={`border-b border-gray-800 ${i % 2 === 0 ? 'bg-gray-900/30' : 'bg-gray-900/60'}`}
                    >
                      <td className="px-6 py-4 font-medium text-gray-300">{row.feature}</td>
                      <td className="px-6 py-4 text-gray-400">{row.fiverr}</td>
                      <td className="px-6 py-4 text-gray-200">{row.runvax}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* How it works */}
          <div className="mb-16">
            <h2 className="text-2xl font-bold mb-8 text-center">
              How Runvax Replaces Fiverr
            </h2>
            <div className="grid md:grid-cols-3 gap-6">
              {[
                {
                  step: '1',
                  title: 'Search any city',
                  body: 'Type Lagos, Accra, London, or any city. Pick an industry. Runvax returns real local businesses with contact details and website status.',
                },
                {
                  step: '2',
                  title: 'Find no-website businesses',
                  body: 'Instantly see which businesses have no website. These are warm leads — they already need what you sell. No cold-calling strangers.',
                },
                {
                  step: '3',
                  title: 'Send AI-written outreach',
                  body: 'Click Generate. Runvax writes a personalized cold email or WhatsApp message for that business in seconds. Send and close.',
                },
              ].map(({ step, title, body }) => (
                <div key={step} className="bg-gray-900 border border-gray-800 rounded-xl p-6">
                  <div className="w-10 h-10 rounded-full bg-indigo-900/50 border border-indigo-700 flex items-center justify-center text-indigo-400 font-bold text-lg mb-4">
                    {step}
                  </div>
                  <h3 className="font-semibold text-lg mb-2">{title}</h3>
                  <p className="text-gray-400 text-sm">{body}</p>
                </div>
              ))}
            </div>
          </div>

          {/* CTA */}
          <div className="rounded-2xl bg-indigo-900/30 border border-indigo-800/50 p-10 text-center">
            <h2 className="text-3xl font-bold mb-3">
              Find your first client today — no Fiverr needed
            </h2>
            <p className="text-gray-400 mb-8 max-w-xl mx-auto">
              Free plan. No credit card. Search any city and find businesses with no website in
              under 60 seconds.
            </p>
            <a
              href="/"
              className="inline-flex items-center gap-2 bg-indigo-600 hover:bg-indigo-500 transition-colors text-white font-semibold px-10 py-4 rounded-xl text-lg"
            >
              Start for free →
            </a>
            <p className="text-gray-600 text-sm mt-4">
              Already on Pro?{' '}
              <a href="/pricing" className="text-indigo-400 hover:underline">
                See all plan features
              </a>
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
